zuul:
  routes:
    ui:
      path: /ui/**
      serviceId: user-ui

    user-provider:
      path: /user-provider/**
      serviceId: user-provider

    auth:
      path: /gate/**
      serviceId: gate


auth:
  token-header: Authorization
  secret: 123456
  expiration: 1000000