spring:
  application:
    name: micro-service
server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#可以关闭密码保护
management:
  security:
    enabled: false