server:
  port: 8081
spring:
  application:
    name: user-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#可以关闭密码保护
management:
  security:
    enabled: false
