eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


zuul:
  addHostHeader: true
  host:
    maxTotalConnections: 2000
    maxPerRouteConnections: 50
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
  #另一种隔离模式的超时时间
  semaphore:
      maxSemaphores: 5000

  ignored-services: '*'  #如果一个服务匹配到了要忽略的列表, 但是它也明确的配置在路由列表中, 将不会被忽略,意思是zuul将忽略所有的路由，但是下面几个还是要路由的

  routes:

    ui:
      path: /ui/**
      serviceId: user-ui

    user-provider:
      path: /user-provider/**
      serviceId: user-provider

    auth:
      path: /gate/**
      serviceId: zuul-gate


auth:
  token-header: access-token
  secret: 123456
  expiration: 1000000